# Generated by Django 4.1 on 2022-08-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Periferico',
                'verbose_name_plural': 'Perifericos',
            },
        ),
        migrations.AlterModelOptions(
            name='notebooks',
            options={'verbose_name': 'Notebook', 'verbose_name_plural': 'Notebooks'},
        ),
    ]
