# Generated by Django 4.1 on 2022-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_notebooks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitores',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monitores/'),
        ),
        migrations.AddField(
            model_name='perifericos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perifericos/'),
        ),
    ]
