# Generated by Django 4.0.6 on 2022-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='address',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
